- name: Get elastic repo
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Uninstall if elasticsearch exist
  yum:
    name: elasticsearch
    state: removed

- name: Remove elasticsearch configs
  file:
    path: /etc/elasticsearch
    state: absent

- name: Clear /var/lib/elasticsearch
  file:
    path: /var/lib/elasticsearch
    state: absent

- name: Install elasticsearch and kibana
  yum: 
    name: 
      - elasticsearch
      - kibana
    state: installed
  notify:
    - Enable services

- name: Apply heap size limit
  copy:
    src: heap_size.options
    dest: /etc/elasticsearch/jvm.options.d/heap_size.options
  notify:
    - Restart elasticsearch

- name: Get elasticsearch config
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart elasticsearch

- name: Ensure elasticsearch is running
  systemd:
    name: elasticsearch
    state: restarted

- name: Ensure kibana is not running
  systemd:
    name: kibana
    state: stopped

- name: Generate elasticsearch passwords
  shell:
    cmd: /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -v -b
  register: elasticsearch_generate_passwords

- name: Debug generated passwords
  debug:
    var: elasticsearch_generate_passwords

- name: Get kibana config
  copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
  notify:
    - Restart kibana


- name: Create k8s index pattern
  uri:
    url: http://{{ hostvars['server-3']['ansible_host'] }}:5601/api/saved_objects/index-pattern/k8s-*?overwrite=true
    method: POST
    body_format: json
    headers:
      kbn-xsrf: this_is_required_header
    body:
      attributes:
        title: "k8s-*"
        timeFieldName: "@timestamp"

- name: Add gitlab repo
  copy:
    src: gitlab-ee.repo
    dest: /etc/yum.repos.d/gitlab-ee.repo

- name: Install gitlab
  yum:
    name: gitlab-ee
  environment:
    EXTERNAL_URL: "http://{{ hostvars['server-3']['ansible_host'] }}"
    GITLAB_ROOT_PASSWORD: "{{ gitlab_password }}"