- name: Get elastic repo
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Install elasticsearch and kibana
  yum: 
    name: 
      - elasticsearch
      - kibana
    state: installed
  notify:
    - Enable services

- name: Apply heap size limit
  copy:
    src: heap_size.options
    dest: /etc/elasticsearch/jvm.options.d/heap_size.options
  notify:
    - Restart elasticsearch

- name: Get kibana config
  copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
  notify:
    - Restart kibana

- name: Get elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart elasticsearch

- name: Create k8s index pattern
  uri:
    method: POST
    headers:
      kbn-xsrf: this_is_required_header
    body_format: json
    body:
      attributes:
        title: "k8s-*"
        timeFieldName: "@timestamp"
    url: http://{{ hostvars['server-3']['ansible_host'] }}:5601/api/saved_objects/index-pattern/k8s-*?overwrite=true
  register: kibana_index_pattern

- name: Debug index pattern request
  debug:
    var: kibana_index_pattern