- name: Get elastic repo
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Install elasticsearch and kibana
  yum: 
    name: 
      - elasticsearch
      - kibana
    state: installed
  notify:
    - Enable services

- name: Apply heap size limit
  copy:
    src: heap_size.options
    dest: /etc/elasticsearch/jvm.options.d/heap_size.options
  notify:
    - Restart elasticsearch

- name: Get kibana config
  copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
  notify:
    - Restart kibana

- name: Get elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch.yml
  notify:
    - Restart elasticsearch
