- name: Restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: yes

- name: Restart kibana
  systemd:
    name: kibana
    state: restarted
    daemon_reload: yes
