#- name: Restart elasticsearch
#  systemd:
#    name: elasticsearch
#    state: restarted
#    daemon_reload: yes
#
#- name: Restart kibana
#  systemd:
#    name: kibana
#    state: restarted
#    daemon_reload: yes
#
#- name: Enable services
#  systemd:
#    name: '{{ item }}'
#    state: started
#    enabled: yes
#  with_items: '{{ installed_services }}'

- name: Reconfigure gitlab
  command:
    cmd: gitlab-ctl reconfigure
