- name: Restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: yes

- name: Restart kibana
  systemd:
    name: kibana
    state: restarted
    daemon_reload: yes

- name: Enable services
  systemd:
    name: '{{ item }}'
    state: enabled
  with_items: '{{ installed_services }}'
