- name: Add hashicorp repo
  get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install consul
  yum:
    name: consul
    state: installed

- name: Create systemd service for consule
  copy:
    src: consule.service
    dest: /etc/systemd/system/consul.service

- name: Replace consul.hcl
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
  notify:
    - Restart consul

- name: Add internal prometheus servide definition
  copy:
    src: prometheus-internal.hcl
    dest: /etc/consul.d/prometheus-internal.hcl
  notify:
    - Restart consul

- name: Validate consul config
  command:
    cmd: consul validate /etc/consul.d/

- name: Flush handlers
  meta: flush_handlers

- name: Get prometheus sha
  uri:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_federation_version }}/sha256sums.txt
    return_content: yes
  register: prometheus_gitlab_sha_file

- name: Extract sha
  command:
    cmd: echo "{{ prometheus_gitlab_sha_file.content }}" | grep linux-amd64 | cut -d " " -f 1
  register: prometheus_sha

- name: Debug checksum
  debug:
    var: prometheus_sha

- name: Get prometheus tar
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_federation_version }}/prometheus-{{ prometheus_federation_version }}.linux-amd64.tar.gz
    dest: /tmp/prometheus-{{ prometheus_federation_version }}.linux-amd64.tar.gz
    checksum: sha256:{{ prometheus_sha.stdout }}
