---
- name: Pull kubespray from Git
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    version: v{{ k8s_kubespray_version }}
    dest: /root/kubespray
    #Descreases idempotency, might improve this later.
    force: yes

- name: Create inventory
  template:
    src: templates/inventory.ini.j2
    dest: /root/kubespray/inventory/sample/inventory.ini

- name: Set cluster name
  lineinfile:
    path:  /root/kubespray/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
    regexp: '^cluster_name:'
    line: 'cluster_name: {{ k8s_cluster_name }}'

- name: Set network plugin
  lineinfile:
    path:  /root/kubespray/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
    regexp: '^kube_network_plugin:'
    line: 'kube_network_plugin: {{ k8s_kube_network_plugin }}'

- name: Set DNS mode
  lineinfile:
    path:  /root/kubespray/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
    regexp: '^dns_mode:'
    line: 'dns_mode: {{ k8s_dns_mode }}'

- name: Install k8s with kubespray
  shell:
    cmd: ansible-playbook -i inventory/sample/inventory.ini  --become --become-user=root cluster.yml
    creates: /usr/local/bin/kubectl
    chdir: /root/kubespray
  register: kubespray-logs
