---
- name: Pull kubespray from git
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    version: v{{ k8s_kubespray_version }}
    dest: /root/kubespray
    #Descreases idempotency, might improve this later.
    force: yes

- name: Create inventory
  template:
    src: templates/inventory.ini.j2
    dest: /root/kubespray/inventory/sample/inventory.ini

- name: Set cluster name
  lineinfile:
    path:  /root/kubespray/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
    regexp: '^cluster_name:'
    line: 'cluster_name: {{ k8s_cluster_name }}'

- name: Set network plugin
  lineinfile:
    path:  /root/kubespray/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
    regexp: '^kube_network_plugin:'
    line: 'kube_network_plugin: {{ k8s_kube_network_plugin }}'

- name: Set dns mode
  lineinfile:
    path:  /root/kubespray/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
    regexp: '^dns_mode:'
    line: 'dns_mode: {{ k8s_dns_mode }}'

- name: Install k8s with kubespray
  #Find alternatives, run all of the roles as another kubespray role? Use ansible import/include?
  shell:
    cmd: ansible-playbook -i inventory/sample/inventory.ini  --become --become-user=root cluster.yml
    creates: /usr/local/bin/kubectl
    chdir: /root/kubespray
  register: kubespray_logs

- name: Get helm tar
  get_url:
    url: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: /root/helm-v{{ helm_version }}-linux-amd64.tar.gz
    checksum: sha256:https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz.sha256sum

- name: Extract helm tar
  unarchive:
    src: /root/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/helm
    exclude:
      - linux-amd64/LICENSE
      - linux-amd64/README.md