---
- name: Pull kubespray
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    version: v{{ k8s_kubespray_version }}
    dest: /root/kubespray
    #Descreases idempotency, might improve this later.
    force: yes

- name: Create inventory
  template:
    src: inventory.ini.j2
    dest: /root/kubespray/inventory/sample/inventory.ini

- name: Set cluster name
  lineinfile:
    path:  /root/kubespray/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
    regexp: '^cluster_name:'
    line: 'cluster_name: {{ k8s_cluster_name }}'

- name: Set network plugin
  lineinfile:
    path:  /root/kubespray/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
    regexp: '^kube_network_plugin:'
    line: 'kube_network_plugin: {{ k8s_kube_network_plugin }}'

- name: Set dns mode
  lineinfile:
    path:  /root/kubespray/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
    regexp: '^dns_mode:'
    line: 'dns_mode: {{ k8s_dns_mode }}'

- name: Check if cluster ready
  uri:
    url: https://localhost:6443/readyz
    return_content: yes
    validate_certs: no
  register: k8s_ready
  ignore_errors: true

- name: Install k8s with kubespray
  #Find alternatives, run all of the roles as another kubespray role? Use ansible import/include?
  command:
    cmd: ansible-playbook -i inventory/sample/inventory.ini  --become --become-user=root cluster.yml
    chdir: /root/kubespray
  when: k8s_ready.content != 'ok'

- name: Create patch for node labes
  copy:
    src: label-patch.yaml
    dest: /tmp/label-patch.yaml

- name: Set label for worker node
  shell:
    cmd: kubectl patch nodes server-0 --patch "$(cat /tmp/label-patch.yaml)"

- name: Get helm tar
  get_url:
    url: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: /tmp/helm-v{{ helm_version }}-linux-amd64.tar.gz
    checksum: sha256:https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz.sha256sum

- name: Extract helm tar
  unarchive:
    src: /tmp/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: /tmp
    creates: /tmp/linux-amd64/helm

- name: Copy helm binary
  copy:
    src: /tmp/linux-amd64/helm
    remote_src: yes
    dest: /usr/local/bin/helm
    mode: u+x,g+x,o+x

- name: Add prometheus-community repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Add ingress-nginx helm repos
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Create prometheus data dir
  file:
    state: directory
    path: /prometheus-data
    mode: o+w

- name: Get prometheus PV yaml
  copy:
    src: prometheus-pv.yaml
    dest: /tmp/prometheus-pv.yaml

- name: Create prometheus PV
  command:
    cmd: kubectl apply -f /tmp/prometheus-pv.yaml

- name: Get prometheus values
  copy:
    src: prometheus-values.yaml
    dest: /tmp/prometheus-values.yaml

- name: Insall prometheus chart
  kubernetes.core.helm:
    name: prometheus
    namespace: monitoring
    chart_ref: prometheus-community/prometheus
    create_namespace: yes
    values_files:
      - /tmp/prometheus-values.yaml

- name: Get nginx ingress controller values
  copy:
    src: nginx-values.yaml
    dest: /tmp/nginx-values.yaml

- name: Insall nginx chart
  kubernetes.core.helm:
    name: ingress-nginx
    namespace: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    create_namespace: yes
    values_files:
      - /tmp/nginx-values.yaml

- name: Get prometheus ingress
  copy:
    src: prometheus-ingress.yaml
    dest: /tmp/prometheus-ingress.yaml

- name: Create ingress for prometheus
  command:
    cmd: kubectl apply -f /tmp/prometheus-ingress.yaml
