---
- name: Install Git
  yum:
    name: git
    state: latest

- name: Pull kubespray from Git
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    version: v{{ k8s_kubespray_version }}
    dest: ~/kubespray
    force: yes

- name: Create inventory
  template:
    src: templates/inventory.ini.j2
    dest: ~/kubespray/inventory/sample/inventory.ini