global:
  scrape_interval: 15s 
  evaluation_interval: 15s
rule_files:
  - "/etc/prometheus/rules/*"
scrape_configs:
  - job_name: "federate"
    honor_labels: true
    metrics_path: /federate
    params:
      'match[]':
      - 'machine_cpu_cores'
      - 'node_cpu_seconds_total'
      - 'kube_pod_container_status_restarts_total'
    consul_sd_configs:
      - services:
        - 'prometheus-int'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"
