- name: Restart consul
  systemd:
    name: consul
    state: restarted
    daemon_reload: yes

- name: Restart prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes

- name: Reload prometheus config
  uri:
    url: "http://localhost:9090/-/reload"
    method: POST
  register: prometheus_reload
  until: prometheus_reload is not failed
  retries: 10

- name: Restart grafana
  systemd:
    name: grafana-server
    state: restarted

- name: Restart alertmanager
  systemd:
    name: alertmanager
    state: restarted
    daemon_reload: yes

- name: Reload alertmanager config
  uri:
    url: "http://localhost:9093/-/reload"
    method: POST
  register: alertmanager_reload
  until: alertmanager_reload is not failed
  retries: 10

- name: Enable services
  systemd:
    name: "{{ item }}"
    with_items: {{ installed_services }}