- name: Restart consul
  service:
    name: consul
    state: restarted

- name: Restart prometheus
  service:
    name: prometheus
    state: restarted

- name: Reload prometheus config
  uri:
    url: "localhost:9090/-/reload"
  register: prometheus_reload 
  until: prometheus_reload is not failed
  retries: 12