alertmanager:
  enabled: false
pushgateway:
  enabled: false
server:
  persistentVolume:
    storageClass: manual
  nodeSelector:
    prometheus_isolation: enabled
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
