groups:
- name: pod_restart
  rules:
  - alert: PodRestart
    expr: increase(kube_pod_container_status_restarts_total[5m]) > 0
    for: 7m
    labels:
      severity: critical
      pod: "{{ $labels.pod }}"
      namespace: "{{ $labels.namespace }}"
      container: "{{ $labels.container }}"
      node: "{{ $labels.node }}"
    annotations:
      summary: Pods restarting frequently