global:
  scrape_interval: 15s 
  evaluation_interval: 15s
scrape_configs:
  - job_name: "federate"
    honor_labels: true
    metrics_path: /federate

    params:
      'match[]':
      - '{__name__=~".+"}'
    consul_sd_configs:
      - services:
        - 'prometheus-int'